version: '3.4'

services:
  demoapp.webapi:
    image: demoappwebapi:dev
    container_name: DemoApp.WebApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DemoApp.WebApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_demoapp.webapi$
    volumes:
      - C:\Users\sivak\source\repos\DemoApp\DemoApp.WebApi:/app
      - C:\Users\sivak\source\repos\DemoApp:/src
      - C:\Users\sivak\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_demoapp.webapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demoapp.webapi$ \"/app/bin/Debug/net6.0/DemoApp.WebApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true